#Controllers
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
    arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
endeffector_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_finger1_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    gripper_finger1_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
#Controller list
controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: endeffector_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home
  - group: endeffector
    pose: open