sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  # should be this one 
  # https://answers.ros.org/question/289556/how-to-obtain-depth-registered-image-from-simulated-kinect-in-gazebo/
    #point_cloud_topic: /camera/depth_registered/points 
    point_cloud_topic: /camera/depth/points
    max_range: 3.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
